spring:
  servlet:
    multipart:
      max-file-size: 20MB #???????20M
      max-request-size: 20MB #???????????20M
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://43.139.46.7:3306/MyServerDB?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    username: root
    password: password
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: 43.139.46.7
    port: 6379
    timeout: 5000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #  global-config:
  #    db-config:
  #      id-type: auto
  #      logic-delete-field: deleteState
  #      logic-delete-value: 1
  #      logic-not-delete-value: 0
  type-aliases-package: cn.wh.mode.pojo #??????????????????
  #  type-enums-package: org.bigjava.novelplatform.common.enums #?????????@EnumValue????????
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
server:
  port: 8080